"""create leaderboard table

Revision ID: 1f3996803bd5
Revises: 28e6c8802fcf
Create Date: 2025-11-15 01:07:56.967517

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f3996803bd5'
down_revision: Union[str, Sequence[str], None] = '28e6c8802fcf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leader_board',
    sa.Column('id', sa.Integer(), primary_key=True, autoincrement=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(), nullable=False),
    sa.Column('scores', sa.Integer(), nullable=False),
    sa.Column('game_name', sa.String(), nullable=False),
    sa.Column('when', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint('scores >= 0', name='ck_leaderboard_scores_positive'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE')
    )
    op.create_index('ix_leader_board_name_scores_game_name', 'leader_board', ['user_name', 'scores', 'game_name'], unique=False)
    op.create_index(op.f('ix_leader_board_user_id'), 'leader_board', ['user_id'], unique=False)
    op.create_index(op.f('ix_leader_board_user_name'), 'leader_board', ['user_name'], unique=False)
    op.drop_index(op.f('ix_friend_requests_requester_status'), table_name='friend_requests')
    op.drop_index(op.f('uq_fr_pending_unordered_pair'), table_name='friend_requests', postgresql_where="((status)::text = 'pending'::text)")
    op.create_unique_constraint('uq_friend_pair', 'friendships', ['user_a_id', 'user_b_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_friend_pair', 'friendships', type_='unique')
    op.create_index(op.f('uq_fr_pending_unordered_pair'), 'friend_requests', [sa.literal_column('LEAST(requester_id, receiver_id)'), sa.literal_column('GREATEST(requester_id, receiver_id)')], unique=True, postgresql_where="((status)::text = 'pending'::text)")
    op.create_index(op.f('ix_friend_requests_requester_status'), 'friend_requests', ['requester_id', 'status'], unique=False)
    op.drop_index(op.f('ix_leader_board_user_name'), table_name='leader_board')
    op.drop_index(op.f('ix_leader_board_user_id'), table_name='leader_board')
    op.drop_index('ix_leader_board_name_scores_game_name', table_name='leader_board')
    op.drop_table('leader_board')
    # ### end Alembic commands ###
