"""add friend models

Revision ID: 33c2dd86e53c
Revises: 49eefd26e2b9
Create Date: 2025-10-25 21:24:06.126186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33c2dd86e53c'
down_revision: Union[str, Sequence[str], None] = '49eefd26e2b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('friend_requests',
    sa.Column('id', sa.Integer(), primary_key=True, autoincrement=True),
    sa.Column('requester', sa.String(), nullable=False),
    sa.Column('receiver', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False, server_default="pending"),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['receiver'], ['users.name'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requester'], ['users.name'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('requester', 'receiver', name='uq_friend_request_pair')
    )
    op.create_index('ix_friend_requests_requester', 'friend_requests', ['requester'])
    op.create_index('ix_friend_requests_receiver', 'friend_requests', ['receiver'])
    op.create_index('ix_friend_requests_receiver_status', 'friend_requests', ['receiver', 'status'])

    op.create_table('friendships',
    sa.Column('user_a', sa.String(), nullable=False),
    sa.Column('user_b', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_a'], ['users.name'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_b'], ['users.name'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_a', 'user_b'),
    sa.UniqueConstraint('user_a', 'user_b', name='uq_friend_pair')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint(None, 'users', type_='unique')
    op.drop_table('friendships')
    op.drop_index(op.f('ix_friend_requests_requester'), table_name='friend_requests')
    op.drop_index('ix_friend_requests_receiver_status', table_name='friend_requests')
    op.drop_index(op.f('ix_friend_requests_receiver'), table_name='friend_requests')
    op.drop_table('friend_requests')
    # ### end Alembic commands ###
