"""add friendship and friendrequest system

Revision ID: 938f4ce2cc82
Revises: e9cf9d999836
Create Date: 2025-10-28 20:02:28.055587

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '938f4ce2cc82'
down_revision: Union[str, Sequence[str], None] = 'e9cf9d999836'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('friend_requests',
    sa.Column('id', sa.Integer(), primary_key=True, autoincrement=True),
    sa.Column('requester_id', sa.Integer(), nullable=False),
    sa.Column('receiver_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False, server_default=sa.text("'pending'")),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', now())"), nullable=False),
    sa.CheckConstraint('requester_id <> receiver_id', name='ck_fr_not_self'),
    sa.ForeignKeyConstraint(['receiver_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requester_id'], ['users.id'], ondelete='CASCADE'),
    sa.UniqueConstraint('requester_id', 'receiver_id', name='uq_friend_request_pair')
    )
    op.create_index(op.f('ix_friend_requests_receiver_id'), 'friend_requests', ['receiver_id'], unique=False)
    op.create_index('ix_friend_requests_receiver_status', 'friend_requests', ['receiver_id', 'status'], unique=False)
    op.create_index(op.f('ix_friend_requests_requester_id'), 'friend_requests', ['requester_id'], unique=False)
    op.create_index('ix_friend_requests_requester_status', 'friend_requests', ['requester_id', 'status'], unique=False)
    op.create_index(
        'uq_fr_pending_unordered_pair',
        'friend_requests',
        [sa.text("LEAST(requester_id, receiver_id)"),
        sa.text("GREATEST(requester_id, receiver_id)")],
        unique=True,
        postgresql_where=sa.text("status = 'pending'")
    )
    op.create_table('friendships',
    sa.Column('user_a_id', sa.Integer(), nullable=False),
    sa.Column('user_b_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('user_a_id <> user_b_id', name='ck_fs_not_self'),
    sa.CheckConstraint('user_a_id < user_b_id', name='ck_fs_canonical_order'),
    sa.ForeignKeyConstraint(['user_a_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_b_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_a_id', 'user_b_id'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('friendships')
    op.drop_index('ix_friend_requests_requester_status', table_name='friend_requests')
    op.drop_index(op.f('ix_friend_requests_requester_id'), table_name='friend_requests')
    op.drop_index('ix_friend_requests_receiver_status', table_name='friend_requests')
    op.drop_index(op.f('ix_friend_requests_receiver_id'), table_name='friend_requests')
    op.drop_index('uq_fr_pending_unordered_pair', table_name='friend_requests')
    op.drop_table('friend_requests')
    # ### end Alembic commands ###
